//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Detail { get; set; }
        public Nullable<int> TargetType { get; set; }
        public Nullable<int> TargetId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CommentStatus { get; set; }
    }
}
