//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> EnquiryStatus { get; set; }
        public string Notes { get; set; }
    }
}
