//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFreight
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateDispatched { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
    }
}
