//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int Id { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CreditCardType { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardExpiry { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string GatewayResponseCode { get; set; }
        public string GatewayResponseVerbose { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
