//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantMenu
    {
        public int Id { get; set; }
        public Nullable<int> ServiceStatus { get; set; }
        public string Name { get; set; }
        public string Brief { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string AssetUrl { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
