//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<bool> SMTPRequiresSSL { get; set; }
        public Nullable<bool> SMTPRequiresTLS { get; set; }
        public Nullable<bool> SMTPRequiresAuth { get; set; }
        public Nullable<int> SMTPSSLPort { get; set; }
        public Nullable<int> SMTPTLSPort { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
    }
}
