//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public Nullable<int> VendorType { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactPosition { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string WebUrl { get; set; }
        public Nullable<int> VendorStatus { get; set; }
    }
}
